FROM dart:3.0.5@sha256:766c9b1109074898931e83cb2151a8ca7be27e978063c83f5130911e776505e0 AS buildimage
ENV HOMEDIR=/atsign
ENV USER_ID=1024
ENV GROUP_ID=1024
WORKDIR /app
# Context for this Dockerfile needs to be at_server repo root 
# If building manually then (from the repo root):
## sudo docker build -t atsigncompany/secondary:dev_obs \
## -f tools/build_secondary/Dockerfile.observe .
COPY ./packages/at_persistence_secondary_server/ ./at_persistence_secondary_server
COPY ./packages/at_secondary_server/ ./at_secondary_server
COPY ./tools/build_virtual_environment/ve_base/contents/atsign/secondary/base/ ./at_secondary_server
RUN \
  cd at_persistence_secondary_server ; \
  dart pub get ; \
  dart pub update ; \
  cd ../at_secondary_server ; \
  dart pub get ; \
  dart pub update ; \
  mkdir -p $HOMEDIR/storage ; \
  mkdir -p $HOMEDIR/config ; \
  mkdir -p /etc/cacert ; \
  mkdir -p /archive ; \
  addgroup --gid $GROUP_ID atsign ; \
  useradd --system --uid $USER_ID --gid $GROUP_ID --shell /bin/bash \
  --home $HOMEDIR atsign ; \
  chown -R atsign:atsign $HOMEDIR ; \
  chown -R atsign:atsign /archive ; \
  chmod -R 755 /usr/lib/dart/ ; \
  chmod -R 755 /root/ ; \
  cp config/config.yaml $HOMEDIR/config/ ; \
  cp cacert/cacert.pem /etc/cacert ; \
  cp pubspec.yaml $HOMEDIR/ ; \
  dart compile jit-snapshot -o secondary.jit bin/main.dart \
    -a @testatsign -p 12345 -s Te$tS3cret -t
# Second stage of build FROM scratch
FROM scratch
COPY --from=buildimage /runtime/ /
COPY --from=buildimage /etc/passwd /etc/passwd
COPY --from=buildimage /etc/group /etc/group
COPY --from=buildimage /etc/cacert /etc/cacert
COPY --from=buildimage --chown=atsign:atsign /app/at_secondary_server/secondary.jit /usr/local/at/
COPY --from=buildimage --chown=atsign:atsign /atsign /atsign/
COPY --from=buildimage --chown=atsign:atsign /archive /archive/
# Minimal viable Dart VM (probably more timming can be done here of snapshots etc.)
COPY --from=buildimage /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
COPY --from=buildimage /usr/lib/dart/bin/snapshots/ /usr/lib/dart/bin/snapshots/
COPY --from=buildimage /usr/lib/dart/bin/resources/devtools/ /usr/lib/dart/bin/resources/devtools/
ENV PATH /usr/lib/dart/bin/
WORKDIR /atsign
USER atsign
ENTRYPOINT ["/usr/lib/dart/bin/dart","run","--observe=8181/0.0.0.0","/usr/local/at/secondary.jit"]