FROM atsigncompany/secondary:canary
ENV HOMEDIR=/atsign
# Context for this Dockerfile needs to be at_server repo root
# If building manually then (from the repo root):
## sudo docker build -t atsigncompany/secondary \
## -f tools/build_secondary/Dockerfile.canary_to_prod .
COPY --chown=1024:1024 ./packages/at_secondary_server/pubspec.yaml $HOMEDIR/
WORKDIR /atsign
USER atsign

ENV DART_VM_OPTIONS='--scavenger_tasks=5,--use_compactor,--marker_tasks=5,--compactor_tasks=5,--idle_duration_micros=10000,--old_gen_growth_time_ratio=50,--old_gen_growth_space_ratio=5,--mark_when_idle'

ENTRYPOINT ["/usr/local/at/secondary"]