version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "/tools/build_secondary"
      - "/tools/build_virtual_environment/ve"
      - "/tools/build_virtual_environment/ve_base"
      - "/packages/at_root_server"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directories:
      - "/packages/at_root_server"
      - "/packages/at_secondary_server"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/tools" # Location of package manifests
    schedule:
      interval: "daily"
