// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:at_persistence_secondary_server/src/log/accesslog/access_entry.dart';
import 'package:at_persistence_secondary_server/src/log/commitlog/commit_entry.dart';
import 'package:at_persistence_secondary_server/src/model/at_data.dart';
import 'package:at_persistence_secondary_server/src/model/at_meta_data.dart';
import 'package:at_persistence_secondary_server/src/notification/at_notification.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    if (!isAdapterRegistered(AccessLogEntryAdapter().typeId)) {
      registerAdapter(AccessLogEntryAdapter());
    }
    if (!isAdapterRegistered(AtDataAdapter().typeId)) {
      registerAdapter(AtDataAdapter());
    }
    if (!isAdapterRegistered(AtMetaDataAdapter().typeId)) {
      registerAdapter(AtMetaDataAdapter());
    }
    if (!isAdapterRegistered(AtNotificationAdapter().typeId)) {
      registerAdapter(AtNotificationAdapter());
    }
    if (!isAdapterRegistered(CommitEntryAdapter().typeId)) {
      registerAdapter(CommitEntryAdapter());
    }
    if (!isAdapterRegistered(CommitOpAdapter().typeId)) {
      registerAdapter(CommitOpAdapter());
    }
    if (!isAdapterRegistered(MessageTypeAdapter().typeId)) {
      registerAdapter(MessageTypeAdapter());
    }
    if (!isAdapterRegistered(NotificationPriorityAdapter().typeId)) {
      registerAdapter(NotificationPriorityAdapter());
    }
    if (!isAdapterRegistered(NotificationStatusAdapter().typeId)) {
      registerAdapter(NotificationStatusAdapter());
    }
    if (!isAdapterRegistered(NotificationTypeAdapter().typeId)) {
      registerAdapter(NotificationTypeAdapter());
    }
    if (!isAdapterRegistered(OperationTypeAdapter().typeId)) {
      registerAdapter(OperationTypeAdapter());
    }
  }
}
