#!/bin/bash
#
if [[ $# -eq 0 || $# -gt 3 ]] ; then
    echo 'Usage create <@sign> <port>'
    exit 0
fi
export env ATSIGN=$1
export env PORT=$2
export env CRAM=$(head -c 32 /dev/urandom | xxd -p -c 32)

echo $ATSIGN
echo $PORT
echo $CRAM
cp  TEMPLATE.conf /etc/supervisor/conf.d/${PORT}_${ATSIGN}.conf
mkdir /atsign/secondary/${ATSIGN}
ln -s /atsign/secondary/base/certs /atsign/secondary/${ATSIGN}/certs
ln -s /atsign/secondary/base/config /atsign/secondary/${ATSIGN}/config
ln -s /atsign/secondary/pubspec.yaml /atsign/secondary/${ATSIGN}/pubspec.yaml
sed -i 's/ATSIGN/'$ATSIGN'/g' /etc/supervisor/conf.d/${PORT}_${ATSIGN}.conf
sed -i 's/CRAM/'$CRAM'/g' /etc/supervisor/conf.d/${PORT}_${ATSIGN}.conf
sed -i 's/PORT/'$PORT'/g' /etc/supervisor/conf.d/${PORT}_${ATSIGN}.conf
echo $CRAM > /atsign/secondary/${ATSIGN}/CRAM

#
#Add records to redis
printf "set ${ATSIGN} vip.ve.atsign.zone:${PORT}\r\n" >> /tmp/records