name: at_end2end_test
description: End to end tests for at_server
publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: optionally-do-not-enforce-namespace

dependencies:
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos.git
      path: at_demo_data
      ref: master
  at_lookup: ^3.0.22
  at_client: ^3.0.20


dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
