name: at_end2end_test
description: End to end tests for at_server
publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos.git
      path: at_demo_data
      ref: master
  at_lookup: ^3.0.29

#dependency_overrides:
#  at_commons:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#      ref: trunk
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: json_decoding_response


dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
