name: at_end2end_test
description: End to end tests for at_server
publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  at_utils:
    path: ../../at_tools/at_utils
  at_commons:
    path: ../../at_tools/at_commons
  at_server_spec:
    path: ../at_server_spec
  at_persistence_secondary_server:
    path: ../at_secondary/at_persistence_secondary_server
  at_secondary:
    path: ../at_secondary/at_secondary_server

dependencies:
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos.git
      path: at_demo_data
      ref: master
  at_lookup: ^3.0.22
  at_client: ^3.0.20


dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
