// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:at_persistence_secondary_server/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccessLogEntryAdapter());
    registerAdapter(AtDataAdapter());
    registerAdapter(AtMetaDataAdapter());
    registerAdapter(AtNotificationAdapter());
    registerAdapter(CommitEntryAdapter());
    registerAdapter(CommitOpAdapter());
    registerAdapter(MessageTypeAdapter());
    registerAdapter(NotificationPriorityAdapter());
    registerAdapter(NotificationStatusAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(OperationTypeAdapter());
  }
}
