FROM atsigncompany/virtualenv:canary
COPY --chown=atsign:atsign ./packages/at_secondary_server/pubspec.yaml /atsign/secondary/
USER root
EXPOSE 64 6379 9001
# Run supervisor configuration file on container startup
CMD ["supervisord", "-n"]