FROM dart:3.11.2@sha256:fd65b23467d84e6470e8050753b976f31229571b79c373b807262d4967aff12b AS buildimage
ENV USER_ID=1024
ENV GROUP_ID=1024
WORKDIR /app
# Context for this Dockerfile needs to be at_server repo root
# If building manually then (from the repo root):
## sudo docker buildx build --platform linux/arm64/v8,linux/amd64 \
## -t atsigncompany/virtualenv:vip \
## -f tools/build_virtual_environment/ve/Dockerfile.vip -o type=registry .
COPY . .
RUN \
  cd /app/packages/at_persistence_secondary_server ; \
  dart pub get ; \
  dart pub update ; \
  cd /app/packages/at_secondary_server ; \
  dart pub get ; \
  dart pub update ; \
  dart compile exe bin/main.dart -o secondary

FROM atsigncompany/vebase:latest
USER root

# Secondary binary and pubspec.yaml from first stage
COPY --from=buildimage --chown=atsign:atsign \
  /app/packages/at_secondary_server/secondary /atsign/secondary/
COPY --from=buildimage --chown=atsign:atsign \
  /app/packages/at_secondary_server/pubspec.yaml /atsign/secondary/

EXPOSE 64 443 6379 9001

ENV DART_VM_OPTIONS="--use_compactor,--use_compactor,--idle_duration_micros=100000,--force_evacuation,--mark_when_idle,--old_gen_growth_time_ratio=50,--old_gen_growth_space_ratio=10"

# Run supervisor configuration file on container startup
CMD ["supervisord", "-n"]
