name: at_persistence_root_server
description: Implementation for root server related persistence.
version: 2.0.5
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_root_server/index.html
publish_to: none

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  at_commons: ^3.0.0
  at_utils: ^3.0.0
  at_persistence_spec: ^2.0.2
  redis: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.3
  mockito: ^5.0.7
  coverage: ^1.0.3
