name: at_persistence_root_server
description: Implementation for root server related persistence.
version: 2.0.5
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_root_server/index.html
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: packages/at_commons
      ref: gkc-new-encryption-metadata-2

dependencies:
  at_persistence_spec: ^2.0.2
  at_utils: ^3.0.0
  at_commons: ^3.0.0
  redis: ^2.0.0

#dependency_overrides:
#  at_persistence_spec:
#    path: ../../at_persistence/at_persistence_spec

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.3
  mockito: ^5.0.7
  coverage: ^1.0.3
