#!/bin/bash

scriptName=$(basename -- "$0")
cd "$(dirname -- "$0")"
scriptDir=$(pwd)

# Script dir is <repo_root>/tools/run_locally/scripts/<platform>
# We will create logs etc in <repo_root>/tools/run_locally/runtime which
# is in .gitignore
cd "$scriptDir"/../../runtime

mkdir -p rootServer
cd rootServer
echo "Running $scriptDir/$scriptName in working directory $(pwd)"

# We need to run a redis server, with a password required.
# (Un-comment "requirepass foobared" in redis.conf)

echo "Starting redis server"
redis-server /usr/local/etc/redis.conf
