name: at_persistence_spec
description: A Dart library to guide implementation of other persistence solutions for servers or SDKs as desired.
version: 2.0.7
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://docs.atsign.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
