name: install_PKAM_Keys
description: Tool to load PKAM keys into root server for testing atSigns
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <4.0.0'

dependencies:
  at_demo_data: ^1.0.0
  at_lookup: ^3.0.12

dependency_overrides:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: dart-3
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos.git
      path: at_demo_data
      ref: dart-3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
