name: install_PKAM_Keys
description: Tool to load PKAM keys into root server for testing atSigns
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos
      path: at_demo_data
      ref: fix/unicode-ve-codepoints
  at_lookup: ^3.0.44

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
