name: at_server_spec
description: A Dart library containing abstract classes that defines what implementations of the root and secondary servers are responsible for.
version: 3.0.12
repository: https://github.com/atsign-foundation/at_server
homepage: https://docs.atsign.com
documentation: https://docs.atsign.com/atplatform/secondaryserver

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  at_commons: ^3.0.48

dev_dependencies:
  lints: ^1.0.1
