name: at_persistence_secondary_server
description: A Dart library with the implementation classes for the persistence layer of the secondary server.
version: 4.1.0
repository: https://github.com/atsign-foundation/at_server
homepage: https://docs.atsign.com/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.2
  hive: ^2.2.3
  cron: ^0.5.0
  crypto: ^3.0.3
  uuid: ^3.0.6
  at_utf7: ^1.0.0
  at_commons: ^5.3.0
  at_utils: ^3.0.19
  at_persistence_spec: ^3.1.0
  meta: ^1.8.0

dependency_overrides:
  at_persistence_spec:
    path: ../at_persistence_spec

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
  coverage: ^1.6.1
  collection: ^1.17.1
