name: at_persistence_secondary_server
description: A Dart library with the implementation classes for the persistence layer of the secondary server.
version: 3.0.57
repository: https://github.com/atsign-foundation/at_server
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  path: ^1.8.2
  hive: ^2.1.0
  cron: ^0.5.0
  crypto: ^3.0.2
  uuid: ^3.0.6
  at_utf7: ^1.0.0
  at_commons: ^3.0.56
  at_utils: ^3.0.15
  at_persistence_spec: ^2.0.14
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  coverage: ^1.6.1
  collection: ^1.17.1
