[program:root_server]
directory = /atsign/root
command = /atsign/bin/at_root_server -h localhost -p 6379 -a foobared
autostart = true
stdout_logfile = /atsign/logs/root_server.log
redirect_stderr = true
username = atsign
autorestart = true
