[program:proxy_server]
command = /bin/sh -c '/atsign/bin/at_proxyserver --proxy-url "${PROXY_URL:-vip.ve.atsign.zone:443}" --root-url vip.ve.atsign.zone:64 --bind-port 1443 --cert-dir /atsign/proxy/certs'
autostart = true
stdout_logfile = /atsign/logs/proxy_server.log
redirect_stderr = true
username = atsign
autorestart = true
