name: at_persistence_secondary_server
description: A Dart library with the implementation classes for the persistence layer of the secondary server.
version: 3.0.14
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_secondary_server/index.html

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  hive: ^2.0.4
  cron: ^0.3.0
  crypto: ^3.0.1
  uuid: ^3.0.4
  at_persistence_spec: ^2.0.3
  at_utils: ^3.0.4
  at_commons: ^3.0.3
  at_utf7: ^1.0.0

dependency_overrides:
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: compaciton_statistics_new
#  at_utils:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_utils
#      ref: trunk
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: trunk

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.1
  coverage: ^1.0.3
