name: at_persistence_secondary_server
description: at_persistence_secondary_server is the Persistence layer implementation for @protocol secondary server.
version: 1.0.1+4
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_secondary_server/index.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  utf7: ^0.2.1
  hive: ^1.3.0
  cron: ^0.2.2
  uuid: ^2.0.2
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: dev_env_staging
      version: ^1.0.1+3

  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: dev_env_staging
      version: ^1.0.1+4

#dependency_overrides:
#  at_persistence_spec:
#    path: ../../../at_server/at_persistence/at_persistence_spec
#  at_utils:
#    path: ../../../at_tools/at_utils
#  at_commons:
#    path: ../../../at_tools/at_commons

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
