name: at_persistence_secondary_server
description: A Dart library with the implementation classes for the persistence layer of the secondary server.
version: 3.0.40
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.2
  hive: ^2.1.0
  cron: ^0.5.0
  crypto: ^3.0.2
  uuid: ^3.0.6
  at_persistence_spec: ^2.0.7
  at_utils: ^3.0.11
  at_commons: ^3.0.25
  at_utf7: ^1.0.0
  meta: ^1.8.0  

dependency_overrides:
#   at_persistence_spec:
#     git:
#       url: https://github.com/atsign-foundation/at_server.git
#       path: at_persistence/at_persistence_spec
#       ref: trunk
#  at_utils:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_utils
#      ref: trunk
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: trunk


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  coverage: ^1.5.0
