[supervisord]
logfile=/atsign/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info
nodaemon=true

[unix_http_server]
file=/atsign/supervisor.sock
chmod=0770

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///atsign/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf /atsign/supervisor/conf.d/*.conf
