name: CA Root Check

on:
  schedule:
    # Runs at 06:26 UTC every Monday
    - cron: '26 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-cacerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Certificate Comparison
        id: compare_cacerts
        working-directory: packages/at_secondary_server/cacert
        run: ${{ github.workspace }}/tools/compare_cacerts.sh

      - name: Google Chat Notification on failure
        if: steps.compare_cacerts.outcome == 'failure'
        uses: atsign-company/google-chat-notification@160671f69e5e29745340c93a819aad68ab9f3f6d # v2.1.0
        with:
          name: Changes found in cacerts
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}