name: CA Root Check

on:
  schedule:
    # Runs at 06:26 UTC every Monday
    - cron: '26 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-cacerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Certificate Comparison
        id: compare_cacerts
        working-directory: packages/at_secondary_server/cacert
        run: ${{ github.workspace }}/tools/compare_cacerts.sh

      - name: Google Chat Notification on failure
        if: steps.compare_cacerts.outcome == 'failure'
        uses: atsign-company/google-chat-notification@69f3920c9c9372c296112b25eaea0bddab9ee115 # v2.0.1
        with:
          name: Changes found in cacerts
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}