name: promote_canary
# Workflow to promote a canary release to production
on:
  push:
    tags:
      - 'p*.*.*'
  workflow_dispatch:

jobs:
  # Deploy canary image to secondary image
  deploy_canary_image_to_prod_secondary_image:
    env:
      working-directory: at_server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      # Extract version for docker tag
      - name: Get version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds and pushes the secondary server image to docker hub.
      - name: Build and push secondary image for amd64 and arm64
        id: docker_build_canary_to_prod
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          file: tools/build_secondary/Dockerfile.canary_to_prod
          context: packages
          tags: |
            atsigncompany/secondary:prod
            atsigncompany/secondary:dess
            atsigncompany/secondary:prod-${{ env.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
