name: promote_canary
# Workflow to promote a canary release to production
on:
  push:
    tags:
      - 'p*.*.*'
  workflow_dispatch:

jobs:
  # Add layer to canary secondary image with prod pubspec.yaml
  deploy_canary_secondary_to_prod_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      # Extract version for docker tag
      - name: Get version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds and pushes the secondary server image to docker hub.
      - name: Build and push secondary image for amd64 and arm64
        id: docker_build_canary_to_prod
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          file: tools/build_secondary/Dockerfile.canary_to_prod
          context: .
          tags: |
            atsigncompany/secondary:prod
            atsigncompany/secondary:dess
            atsigncompany/secondary:prod-${{ env.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7

  # Add layer to canary virtualenv image with prod pubspec.yaml
  deploy_canary_virtualenv_to_prod_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      # Extract version for docker tag
      - name: Get version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds and pushes the secondary server image to docker hub.
      - name: Build and push virtualenv image for amd64 and arm64
        id: docker_build_canary_to_vip
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          file: tools/build_virtual_environment/ve/Dockerfile.canary_to_vip
          context: .
          tags: |
            atsigncompany/virtualenv:vip
            atsigncompany/virtualenv:vip-${{ env.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64/v8
