name: Refreshcerts
on:
  workflow_dispatch:
  schedule:
    - cron: '39 7 15 * *' # At 0739 on the 15th day of every month

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  refresh-ACME-cert:
    runs-on: ubuntu-24.04
    name: SSL Renewal for vip.ve.atsign.zone
    steps:
      - name: setup certinfo
        uses: atsign-company/certinfo-action@e33db584f27bbbc0260af9916aeaefbec0db8ef4 # v1.0.1
      # checkout at_server code
      - name: checkout repo content
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # Pull ACME script
      - name: Pull ACME script
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: atsign-company/secondaries-scripts
          path: secondaries-scripts
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          ref: trunk
      # Create required directory, and copy keys files from secrets
      - name: Create required directory and pull secrets
        run: |-
          sudo mkdir -p /gluster/@/api/keys
          sudo chmod -R 777 /gluster/@/api/keys
          echo "${{secrets.DUMMY_PRIVKEY}}" > /gluster/@/api/keys/dummy.key
          echo "${{secrets.LETSENCRYPT_PRIVKEY}}" > /gluster/@/api/keys/letsencrypt.key
          echo "${{secrets.ZEROSSL_PRIVKEY}}" > /gluster/@/api/keys/zerossl.key
          echo "${{secrets.GOOGLE_PRIVKEY}}" > /gluster/@/api/keys/google.key
      # Install Python Libraries
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - name: Install Python Libraries
        run: |-
          sudo apt-get install python3-poetry-plugin-export
          uv venv
          . .venv/bin/activate
          cd tools
          poetry export --format requirements.txt --output requirements.txt
          uv pip install --require-hashes -r requirements.txt
      # Ensure runner trusts our CA
      - name: Add Custom CA to Runner Trust Store
        run: |
          echo "${{ vars.PRODCA }}" | sudo tee /usr/local/share/ca-certificates/stepcaprod.crt > /dev/null
          sudo update-ca-certificates
      # Install NoPorts and atKeys
      - name: Setup NoPorts and Authentication
        uses: atsign-foundation/noports-action@464b931232f49cd302ecf5eb913cfe2c778fbd6e # v1.0.0
        with:
          atsign: '@stepcaprod'
          atkeys-secret: ${{ secrets.ATKEYS_STEPCAPROD }}
      # Connect to the Atsign Prod CA
      - name: Establish a NoPorts tunnel
        run: |
          nohup npt -f stepcaprod -t cookingthelemon -r rv_am -d stepcaprod \
            -l 3443 -p 3443 --rh 127.0.0.1 --lh 127.0.0.1 -T 0 \
            > npt.log 2> npt.err < /dev/null &
          tail -f npt.err | grep -m 1 "npt is listening"
      # Test npt connection to prod CA
      - name: Test npt connection to prod CA
        run: |
          curl https://ca.atsign.org:3443/acme/acme/directory
      # Create and copy certs (mTLS first)
      - name: Run create_cert scripts then copy certs to right place
        run: |-
          chmod -R 777 secondaries-scripts
          . .venv/bin/activate
          cd secondaries-scripts/sec_ops
          ./create_mtls_workflow.sh vip.ve.atsign.zone
          cp mtls/privkey.pem ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/secondary/base/certs/mtls/
          cp mtls/fullchain.pem ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/secondary/base/certs/mtls/
          cp ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/secondary/base/certs/mtls/*.pem \
            ${WS}/tools/build_ephemeral_environment/ee_base/contents/atsign/secondary/base/certs/mtls/
          ./create_cert_workflow.sh vip.ve.atsign.zone
          cp privkey.pem ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/root/certs/privkey.pem
          cp fullchain.pem ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/root/certs/fullchain.pem
          cp ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/root/certs/*.pem \
            ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/secondary/base/certs/
          cp ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/root/certs/*.pem \
            ${WS}/tools/build_ephemeral_environment/ee_base/contents/atsign/root/certs/
          cp ${WS}/tools/build_virtual_environment/ve_base/contents/atsign/root/certs/*.pem \
            ${WS}/tools/build_ephemeral_environment/ee_base/contents/atsign/secondary/base/certs/
          cd ${WS} && rm -rf secondaries-scripts
        env:
          WS: ${{ github.workspace }}
          DO_KEY: ${{ secrets.DO_KEY }}
          gChat_url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          # Python in venv will use certifi trust store by default
          REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      # create PR with renewed certificates
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: 'chore: New certificates for at_server'
          committer: library-action[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: library-action[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          add-paths: |
            ./tools/build_ephemeral_environment
            ./tools/build_virtual_environment
          branch: bot-new-certs
          delete-branch: true
          title: 'chore: New certificates generated'
          body: |
            Fresh certificates generated.
          labels: |
            operations
          assignees: cpswan
          reviewers: gkc
          draft: false
