name: Bump requirements.txt
on:
  pull_request:
    paths:
      - 'tools/pyproject.toml'
  workflow_dispatch:

permissions:
  pull-requests: write
  
jobs:
  bump_requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Set up Python
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
          python-version: '3.11'

    - name: Install Poetry
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439 # v3.0.0
      with:
        poetry-version: '1.8.2'
    
    - name: Bump Python dependencies
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: |
        cd tools
        poetry update
        poetry export --format requirements.txt --output requirements.txt
        git config --global user.name 'dependabot[bot]'
        git config --global user.email 'dependabot[bot]@users.noreply.github.com'
        git add requirements.txt
        if [ -z "$(git status --porcelain)" ]; then 
          echo 'No changes to commit on this run'
          exit 0
        else
          git commit -m "build(deps): Bump requirements.txt"
          git push
        fi
