name: VE_base
on:
  workflow_dispatch:
  schedule:
    - cron: "42 6 * * 1" # At 0642 each Monday

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ve_base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: "ve_base"
            name: "vebase"
          - dir: "dynamic_ve_base"
            name: "dynamicvebase"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        with:
          file: tools/build_virtual_environment/${{matrix.dir}}/Dockerfile
          push: true
          tags: |
            atsigncompany/${{matrix.name}}:latest
            atsigncompany/${{matrix.name}}:${{matrix.dir}}-gha${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@3691ccf4763537d6e544bc6cdcccc1965799d056 # v1
        with:
          name: New Docker base image for ${{matrix.name}}:latest
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
