name: vip_rebuild
# Creates a new image for atsigncompany/virtualenv:vip whenever updated
# certificates are merged to trunk
on:
  push:
    branches:
      - trunk
    paths:
      - 'tools/build_virtual_environment/ve_base/contents/atsign/root/certs/fullchain.pem'
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ve_base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Checkout trunk
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to DockerHub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          tags: |
            type=raw,value=latest
            type=raw,value=vip_rebuild-gha${{ github.run_number }}
          images: |
            atsigncompany/vebase
          labels: |
            org.opencontainers.image.description=Base image for Atsign Virtual Environment

      - name: Build and push new VE base
        id: docker_build_base
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          file: tools/build_virtual_environment/ve_base/Dockerfile
          push: true
          sbom: true
          provenance: version=v1,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_base.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Image digest VE base
        run: echo ${{ steps.docker_build_base.outputs.digest }}

      - name: Google Chat Notification VE base
        uses: Co-qn/google-chat-notification@3691ccf4763537d6e544bc6cdcccc1965799d056 # v1
        with:
          name: New Docker base image for vebase:latest
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

  push_prod_virtualenv_image:
    needs: [ ve_base ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Get latest production tag
        id: prod_tag
        run: |
          REPO="https://api.github.com/repos/atsign-foundation/at_server/releases/latest"
          PROD_TAG=$(curl -s ${REPO} | jq -r .tag_name)
          echo "prod_tag=${PROD_TAG}" >> $GITHUB_OUTPUT

      - name: Checkout latest production tag
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ steps.prod_tag.outputs.prod_tag}}

      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to DockerHub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          tags: |
            type=raw,value=vip
            type=raw,value=vip_rebuild-gha${{ github.run_number }}
          images: |
            atsigncompany/virtualenv

      - name: Build and push vip
        id: docker_build_vip
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          file: tools/build_virtual_environment/ve/Dockerfile.vip
          context: .
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64/v8

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_vip.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Image digest vip
        run: echo ${{ steps.docker_build_vip.outputs.digest }}

      - name: Google Chat Notification vip
        uses: Co-qn/google-chat-notification@3691ccf4763537d6e544bc6cdcccc1965799d056 # v1
        with:
          name: New Docker image for atsigncompany/virtualenv:vip
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

  push_prod_ephemeral_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Get latest production tag
        id: prod_tag
        run: |
          REPO="https://api.github.com/repos/atsign-foundation/at_server/releases/latest"
          PROD_TAG=$(curl -s ${REPO} | jq -r .tag_name)
          echo "prod_tag=${PROD_TAG}" >> $GITHUB_OUTPUT

      - name: Checkout latest production tag
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ steps.prod_tag.outputs.prod_tag}}

      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to DockerHub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          tags: |
            type=raw,value=latest
            type=raw,value=vip_rebuild-gha${{ github.run_number }}
          images: |
            atsigncompany/ephemeral

      - name: Build and push ephemeral
        id: docker_build_ephemeral
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          file: tools/build_ephemeral_environment/ee_base/Dockerfile
          context: .
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64/v8

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_ephemeral.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Image digest EE
        run: echo ${{ steps.docker_build_vip.outputs.digest }}

      - name: Google Chat Notification EE
        uses: Co-qn/google-chat-notification@3691ccf4763537d6e544bc6cdcccc1965799d056 # v1
        with:
          name: New Docker image for atsigncompany/ephemeral
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
