name: vip_rebuild
# Creates a new image for atsigncompany/virtualenv:vip whenever updated
# certificates are merged to trunk
on:
  push:
    branches:
      - trunk
    paths:
      - 'tools/build_virtual_environment/ve_base/contents/atsign/root/certs/fullchain.pem'
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ve_base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Checkout trunk
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,value=latest
            type=raw,value=vip_rebuild-gha${{ github.run_number }}
          images: |
            atsigncompany/vebase
          labels: |
            org.opencontainers.image.description=Base image for Atsign Virtual Environment

      - name: Build and push new VE base
        id: docker_build_base
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: tools/build_virtual_environment/ve_base/Dockerfile
          push: true
          sbom: true
          provenance: version=v1,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_base.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Image digest VE base
        run: echo ${{ steps.docker_build_base.outputs.digest }}

      - name: Google Chat Notification VE base
        uses: Co-qn/google-chat-notification@3691ccf4763537d6e544bc6cdcccc1965799d056 # v1
        with:
          name: New Docker base image for vebase:latest
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

  push_prod_virtualenv_image:
    needs: [ ve_base ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Get latest production tag
        id: prod_tag
        run: |
          REPO="https://api.github.com/repos/atsign-foundation/at_server/releases/latest"
          PROD_TAG=$(curl -s ${REPO} | jq -r .tag_name)
          echo "prod_tag=${PROD_TAG}" >> $GITHUB_OUTPUT

      - name: Checkout latest production tag
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ steps.prod_tag.outputs.prod_tag}}

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,value=vip
            type=raw,value=vip_rebuild-gha${{ github.run_number }}
          images: |
            atsigncompany/virtualenv

      - name: Build and push vip
        id: docker_build_vip
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: tools/build_virtual_environment/ve/Dockerfile.vip
          context: .
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64/v8

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_vip.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Image digest vip
        run: echo ${{ steps.docker_build_vip.outputs.digest }}

      - name: Google Chat Notification vip
        uses: Co-qn/google-chat-notification@3691ccf4763537d6e544bc6cdcccc1965799d056 # v1
        with:
          name: New Docker image for atsigncompany/virtualenv:vip
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

  push_prod_ephemeral_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    steps:
      - name: Get latest production tag
        id: prod_tag
        run: |
          REPO="https://api.github.com/repos/atsign-foundation/at_server/releases/latest"
          PROD_TAG=$(curl -s ${REPO} | jq -r .tag_name)
          echo "prod_tag=${PROD_TAG}" >> $GITHUB_OUTPUT

      - name: Checkout latest production tag
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ steps.prod_tag.outputs.prod_tag}}

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,value=latest
            type=raw,value=vip_rebuild-gha${{ github.run_number }}
          images: |
            atsigncompany/ephemeral

      - name: Build and push ephemeral
        id: docker_build_ephemeral
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: tools/build_ephemeral_environment/ee_base/Dockerfile
          context: .
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64/v8

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_ephemeral.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Image digest EE
        run: echo ${{ steps.docker_build_vip.outputs.digest }}

      - name: Google Chat Notification EE
        uses: atsign-company/google-chat-notification@69f3920c9c9372c296112b25eaea0bddab9ee115 # v2.0.1
        with:
          name: New Docker image for atsigncompany/ephemeral
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
